from typing import TypedDict, Optional, Any

class AgentState(TypedDict):
    """
    Shared state passed between LangGraph nodes.
    """

    # User's original question
    query: str

    # Tool selected by the router
    # market | option_chain | pdf | general
    route: Optional[str]

    # Output returned by the selected retriever
    retrieved_context: Optional[Any]

    # Final answer generated by the LLM
    answer: Optional[str]